process
    .on('uncaughtException', (err) => {
    console.error(err.message);
    process.exit(1);
})
    .on('unhandledRejection', (reason) => {
    console.error(reason.message);
    process.exit(1);
});
